### ISSUE TITLE
How to build this package manually for osx-arm64

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-standalone-feedstock#72]
From an `osx-arm64` machine, [follow this comment](https://github.com/conda-forge/conda-standalone-feedstock/pull/71#issuecomment-1894135996):

This is the `.ci_support/osx_arm64_.yml` file to use locally (not available in this repo):

```yaml
MACOSX_DEPLOYMENT_TARGET:
- '11.0'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
macos_machine:
- arm64-apple-darwin20.0.0
target_platform:
- osx-arm64
```

Then run command off current `main` (with the relevant PR freshly merged):

```
MINIFORGE_HOME=~/opt/miniforge OSX_SDK_DIR=~/opt python build-locally.py osx_arm64_ 2>&1 | tee log.txt 
```

Upload the resulting artifact from `$MINIFORGE_HOME/conda-bld/osx-arm64`:

```
anaconda upload -u $USER_CHANNEL -l conda-standalone-$VERSION-$BUILD ~/opt/miniforge/conda-bld/osx-arm64/conda-standalone-*
```

Then, upload the compressed `log.txt` to a comment in the freshly merged PR, as well as a link to the channel you uploaded the artifact to.

Once posted, request a review from a core member. Once approved, you can copy the artifact to conda-forge via:

```
anaconda copy --from-label conda-standalone-$VERSION-$BUILD --to-label main --to-owner conda-forge $USER_CHANNEL/conda-standalone/$VERSION
```
